# Generated by Django 5.1.7 on 2025-03-20 13:14

import author.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('c18c54c2-9079-421d-8b72-26d3c11e5042'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, validators=[author.validators.validate_non_empty])),
            ],
        ),
    ]
